---
<<<<<<< HEAD
- hosts: localhost
  gather_facts: yes 
=======
- hosts: app_server
  remote_user: ubuntu
>>>>>>> 447913d45161636883cca91de546062b425a1e45
  pre_tasks:
  - name: Include vars
    include_vars: vars/main.yml
  - apt: update_cache=yes
    become: yes
  tasks:
  - name: Send notification message via Slack all options
    slack:
      token: "xoxp/9829409589/17630400722/90192379762/a739d5fcb915a8b7dfd675f1cdd7e01d"
      domain: notinphilly.slack.com
      msg: "{{ inventory_hostname }} completed"
      channel: "#devops"
      username: "alex.lubneuski"
      icon_url: "https://cdn.meme.am/instances/35478200.jpg"
      link_names: 0
      parse: 'none'
    tags: send_slack 
    when: enable_slack == 'True'
  roles: 
  - nodejs
  - { role: notinphilly, syslevel: "{{ sysLevel }}", install_dir: "{{ installDir }}", app_name: "{{ appName }}", aws_mongo_db_url: "mongodb://{{ DB_SERVER }}/notinphilly", openshift_nodejs_ip: "0.0.0.0", email_api_key: "{{ EMAIL_API_KEY }}", email_domain: '{{ EMAIL_DOMAIN }}', map_box_api_key: "{{ MAP_BOX_API_KEY }}", map_box_map_id: "{{ MAP_BOX_MAP_ID }}", google_api_key: "{{ GOOGLE_API_KEY }}", secret_token: "{{ SECRET_TOKEN }}", http_ip: "{{ HTTP_IP }}", http_port: "{{ HTTP_PORT  }}", db_connection_string: "mongodb://{{ DB_SERVER }}/notinphilly", url_to_follow: "{{ public_elb_url }}" }
