---
- name: include vars 
  include_vars: vars/main.yml
- name: Install nodejs
  command: yum install -y nodejs npm --enablerepo=epel
  become: yes
- name: Install git
  yum: name=git state=present
  become: yes
- name: Install bower
  command: npm install -g  bower 
  become: yes
- name: Install forever
  command: npm install -g forever
  become: yes
