---
- name: include vars 
  include_vars: vars/main.yml
- apt: name=git state=present
  become: yes
- name: Install nodejs
  apt: name=nodejs state=present 
  become: yes
- apt: name=nodejs-legacy state=present
  become: yes
- name: Install npm
  apt: name=npm state=present
  become: yes
- name: Install bower
  command: npm install bower -g
  become: yes
- name: Install forever
  command:  npm install forever -g
  become: yes
