---
- name: Stop everything
  command: forever stopall
- name: Remove directories
  command: rm -rf ~/srv/notinphilly
- name: Include Variables
  include_vars: vars/main.yml
- name: Create directory
  file: path="./srv/{{ app_name }}" state=directory mode=0755
- name: Get checkout code from Jenkins
  synchronize: src=/var/lib/jenkins/workspace/notinphilly_app_deploy_dev/ dest=./srv/{{ app_name }}/
- name: Run bower install
  command: bower install -f
  args:
    chdir: "{{ install_dir }}/{{ app_name }}"
- name: Install npm dependencies
  command: npm install
  args:
    chdir: "{{ install_dir }}/{{ app_name }}"
- name: Check which apps are running
  command: forever list
  register: forever_list
  changed_when: false 
  ignore_errors: true
- name: Start server
  command: forever start server.js
  when: "forever_list.stdout.find('{{ install_dir }}/{{ app_name }}/server.js') == -1"
  args:
    chdir: "{{ install_dir }}/{{ app_name }}"
  environment:
    AWS_MONGO_DB_URL: "mongodb://10.1.4.103/notinphilly"
    OPENSHIFT_NODEJS_IP: "0.0.0.0"
    EMAIL_API_KEY: "key-9c7663b6947df059523a2c1081483fbc"
    EMAIL_DOMAIN: 'mail.notinphilly.org'
    MAP_BOX_API_KEY: "pk.eyJ1IjoieXVyeWtvcnp1biIsImEiOiJjaXVsbHBnOTgwMDc4MnlwazkxYWhoNnY2In0.iU-SAfTXEZSsTEJK74wfeA"
    MAP_BOX_MAP_ID: "yurykorzun.nljndeg0"
    GOOGLE_API_KEY: "AIzaSyAUptjRjLzbBPVOUu2PxQhOLQ5DSNAPEX8"
    SECRET_TOKEN: "notinphillynotinphilly"
    HTTP_IP: "0.0.0.0"
    HTTP_PORT: "8080"
    DB_CONNECTION_STRING_: "mongodb://10.1.4.103/notinphilly"
